# Generated by Django 6.0.5 on 2026-05-25 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost price per unit', max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, help_text='Wholesale selling price', max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, help_text='Retail selling price', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Default discount %', max_digits=5)),
                ('quantity', models.IntegerField(default=0)),
                ('min_stock_level', models.IntegerField(default=10, help_text='Minimum quantity before low stock alert')),
                ('unit_type', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('bottle', 'Bottle'), ('strip', 'Strip'), ('box', 'Box'), ('pack', 'Pack'), ('ml', 'Milliliter'), ('g', 'Gram')], default='tablet', max_length=20)),
                ('units_per_pack', models.IntegerField(default=1, help_text='Number of units per pack/strip/bottle')),
                ('expiry_date', models.DateField()),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('barcode', models.CharField(blank=True, help_text='QR/Bar code for scanning', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.supplier')),
            ],
            options={
                'db_table': 'medicines',
                'indexes': [models.Index(fields=['name'], name='medicines_name_017048_idx'), models.Index(fields=['expiry_date'], name='medicines_expiry__a56ade_idx')],
            },
        ),
    ]
