# Generated by Django 6.0.5 on 2026-05-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=15)),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_license', models.CharField(blank=True, max_length=100)),
                ('hospital', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('diagnosis', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('partially_filled', 'Partially Filled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('prescription_image', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_quantity', models.IntegerField()),
                ('filled_quantity', models.IntegerField(default=0)),
                ('dosage_instructions', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'prescription_items',
            },
        ),
    ]
